# Generated by Django 5.1 on 2024-08-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название заголовка')),
                ('slug', models.CharField(max_length=100, verbose_name='slug')),
                ('content', models.TextField(max_length=200, verbose_name='содержимое')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photo/blog', verbose_name='Изображение')),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='дата создания')),
                ('is_publication', models.BooleanField(default=True, verbose_name='Признак публикации')),
                ('count_views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
