# Generated by Django 5.1.1 on 2024-09-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_cancel_publication', 'Может отменять публикацию продукта'), ('can_change_description_product', 'может менять описание любого продукта'), ('can_change_category_product', 'может менять категорию любого продукта')], 'verbose_name': 'плагин', 'verbose_name_plural': 'плагины'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_publication',
            field=models.BooleanField(default=False, verbose_name='Признак публикации'),
        ),
    ]
